# Generated by Django 4.2.8 on 2024-07-17 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Generate_PDF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateinvoice',
            name='method_paid',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
