# Generated by Django 5.0.6 on 2024-05-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
