# Generated by Django 5.0.6 on 2024-06-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageLogin', '0003_customuser_name_of_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_admin',
            new_name='adminCollege',
        ),
    ]
